import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { gql, useQuery } from '@apollo/client'

import styles from '../styles/Home.module.css'

const GET_TODOS = gql`
  query getTodos {
    todos {
      id
      label
      done
    }
  }
`

const Home: NextPage = () => {
  const { loading, error, data } = useQuery(GET_TODOS)

  console.log(loading, error, data)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        {loading && <p>Loading...</p>}

        {error && <p>Error loading!</p>}

        {data?.todos?.length < 1 && <p>No todos</p>}

        <ul>
          {data?.todos?.map((i: any) => (
            <li key={`todo_${i.id}`}>
              {i.label} - {i.done ? 'Complete' : 'Incomplete'}
            </li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
